'ES', 'E♭'           
'AS', 'A♭'           
'HES', 'B♭'          
'HIS', 'B♯'          
'H ES', 'B♭'         
'H IS', 'B♯'         
'es', 'E♭'           
'as', 'A♭'           
'hes', 'B♭'          
'his', 'B♯'          
'h es', 'B♭'         
'h is', 'B♯'         
'DOBEMOL', 'C♭'      
'DOBEMOLLE', 'C♭'    
'DOBÉMOL', 'C♭'      
'DOFLAT', 'C♭'       
'DO#', 'C♯'          
'DOSOSTENIDO', 'C♯'  
'DODIESIS', 'C♯'     
'DODIÈSE', 'C♯'      
'DOSHARP', 'C♯'      
'UTBEMOL', 'C♭'      
'UTBEMOLLE', 'C♭'    
'UTBÉMOL', 'C♭'      
'UTFLAT', 'C♭'       
'UT#', 'C♯'          
'UTSOSTENIDO', 'C♯'  
'UTDIESIS', 'C♯'     
'UTDIÈSE', 'C♯'      
'UTSHARP', 'C♯'      
'DO BEMOL', 'C♭'     
'DO BEMOLLE', 'C♭'   
'DO BÉMOL', 'C♭'     
'DO FLAT', 'C♭'      
'DO #', 'C♯'         
'DO SOSTENIDO', 'C♯' 
'DO DIESIS', 'C♯'    
'DO DIÈSE', 'C♯'     
'DO SHARP', 'C♯'     
'UT BEMOL', 'C♭'     
'UT BEMOLLE', 'C♭'   
'UT BÉMOL', 'C♭'     
'UT FLAT', 'C♭'      
'UT #', 'C♯'         
'UT SOSTENIDO', 'C♯' 
'UT DIESIS', 'C♯'    
'UT DIÈSE', 'C♯'     
'UT SHARP', 'C♯'     
'CBEMOL', 'C♭'       
'CBEMOLLE', 'C♭'     
'CBÉMOL', 'C♭'       
'CFLAT', 'C♭'        
'C#', 'C♯'           
'CSOSTENIDO', 'C♯'   
'CDIESIS', 'C♯'      
'CDIÈSE', 'C♯'       
'CSHARP', 'C♯'       
'C BEMOL', 'C♭'      
'C BEMOLLE', 'C♭'    
'C BÉMOL', 'C♭'      
'C FLAT', 'C♭'       
'C #', 'C♯'          
'C SOSTENIDO', 'C♯'  
'C DIESIS', 'C♯'     
'C DIÈSE', 'C♯'      
'C SHARP', 'C♯'      
'dobemol', 'C♭'      
'dobemolle', 'C♭'    
'dobémol', 'C♭'      
'doflat', 'C♭'       
'do#', 'C♯'          
'dosostenido', 'C♯'  
'dodiesis', 'C♯'     
'dodièse', 'C♯'      
'dosharp', 'C♯'      
'utbemol', 'C♭'      
'utbemolle', 'C♭'    
'utbémol', 'C♭'      
'utflat', 'C♭'       
'ut#', 'C♯'          
'utsostenido', 'C♯'  
'utdiesis', 'C♯'     
'utdièse', 'C♯'      
'utsharp', 'C♯'      
'do bemol', 'C♭'     
'do bemolle', 'C♭'   
'do bémol', 'C♭'     
'do flat', 'C♭'      
'do #', 'C♯'         
'do sostenido', 'C♯' 
'do diesis', 'C♯'    
'do dièse', 'C♯'     
'do sharp', 'C♯'     
'ut bemol', 'C♭'     
'ut bemolle', 'C♭'   
'ut bémol', 'C♭'     
'ut flat', 'C♭'      
'ut #', 'C♯'         
'ut sostenido', 'C♯' 
'ut diesis', 'C♯'    
'ut dièse', 'C♯'     
'ut sharp', 'C♯'     
'cbemol', 'c♭'       
'cbemolle', 'c♭'     
'cbémol', 'c♭'       
'cflat', 'c♭'        
'c#', 'c♯'           
'csostenido', 'c♯'   
'cdiesis', 'c♯'      
'cdièse', 'c♯'       
'csharp', 'c♯'       
'c bemol', 'c♭'      
'c bemolle', 'c♭'    
'c bémol', 'c♭'      
'c flat', 'c♭'       
'c #', 'c♯'          
'c sostenido', 'c♯'  
'c diesis', 'c♯'     
'c dièse', 'c♯'      
'c sharp', 'c♯'